# Generated by Django 6.0 on 2026-01-03 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_company_alter_user_options_user_first_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Single", "Single"),
                            ("Married", "Married"),
                            ("Divorced", "Divorced"),
                        ],
                        max_length=20,
                    ),
                ),
                ("residential_address", models.TextField(blank=True)),
                ("personal_email", models.EmailField(blank=True, max_length=254)),
                ("department", models.CharField(blank=True, max_length=100)),
                ("job_title", models.CharField(blank=True, max_length=100)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("bank_name", models.CharField(blank=True, max_length=100)),
                ("account_number", models.CharField(blank=True, max_length=50)),
                ("ifsc_code", models.CharField(blank=True, max_length=20)),
                ("pan_no", models.CharField(blank=True, max_length=20)),
                ("uan_no", models.CharField(blank=True, max_length=20)),
                (
                    "monthly_wage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "yearly_wage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("working_days_per_week", models.IntegerField(default=5)),
                (
                    "break_time_hours",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
                ),
                (
                    "basic_salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "basic_salary_percent",
                    models.DecimalField(decimal_places=2, default=50.0, max_digits=5),
                ),
                (
                    "house_rent_allowance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "hra_percent",
                    models.DecimalField(decimal_places=2, default=50.0, max_digits=5),
                ),
                (
                    "standard_allowance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "standard_allowance_percent",
                    models.DecimalField(decimal_places=2, default=16.67, max_digits=5),
                ),
                (
                    "performance_bonus",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "performance_bonus_percent",
                    models.DecimalField(decimal_places=2, default=8.33, max_digits=5),
                ),
                (
                    "leave_travel_allowance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "lta_percent",
                    models.DecimalField(decimal_places=2, default=8.33, max_digits=5),
                ),
                (
                    "fixed_allowance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "fixed_allowance_percent",
                    models.DecimalField(decimal_places=2, default=11.67, max_digits=5),
                ),
                (
                    "professional_tax",
                    models.DecimalField(decimal_places=2, default=200.0, max_digits=10),
                ),
                (
                    "pf_employee_contribution",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "pf_employee_percent",
                    models.DecimalField(decimal_places=2, default=12.0, max_digits=5),
                ),
                (
                    "pf_employer_contribution",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "pf_employer_percent",
                    models.DecimalField(decimal_places=2, default=12.0, max_digits=5),
                ),
                (
                    "about",
                    models.TextField(
                        blank=True, help_text="About section for employee profile"
                    ),
                ),
                (
                    "skills",
                    models.JSONField(
                        blank=True, default=list, help_text="List of skills"
                    ),
                ),
                (
                    "certifications",
                    models.JSONField(
                        blank=True, default=list, help_text="List of certifications"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subordinates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Profile",
                "verbose_name_plural": "Employee Profiles",
                "db_table": "employee_profiles",
            },
        ),
        migrations.CreateModel(
            name="TimeOff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_off_type",
                    models.CharField(
                        choices=[
                            ("PAID", "Paid Time Off"),
                            ("SICK", "Sick Leave"),
                            ("UNPAID", "Unpaid Leave"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("total_days", models.IntegerField(default=1)),
                ("reason", models.TextField(blank=True)),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="leave_certificates/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_leaves",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_off_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Time Off",
                "verbose_name_plural": "Time Off Requests",
                "db_table": "time_off",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("check_in", models.TimeField(blank=True, null=True)),
                ("check_out", models.TimeField(blank=True, null=True)),
                (
                    "work_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "extra_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRESENT", "Present"),
                            ("ABSENT", "Absent"),
                            ("LEAVE", "On Leave"),
                        ],
                        default="ABSENT",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance",
                "verbose_name_plural": "Attendance Records",
                "db_table": "attendance",
                "ordering": ["-date"],
                "unique_together": {("user", "date")},
            },
        ),
        migrations.CreateModel(
            name="LeaveAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(default=2026)),
                ("paid_leave_total", models.IntegerField(default=24)),
                ("paid_leave_used", models.IntegerField(default=0)),
                ("sick_leave_total", models.IntegerField(default=7)),
                ("sick_leave_used", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_allocations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Leave Allocation",
                "verbose_name_plural": "Leave Allocations",
                "db_table": "leave_allocations",
                "unique_together": {("user", "year")},
            },
        ),
    ]
