# Generated by Django 6.0 on 2026-01-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_employeeprofile_timeoff_attendance_leaveallocation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("PRESENT", "Present"),
                    ("ABSENT", "Absent"),
                    ("HALF_DAY", "Half Day"),
                    ("LEAVE", "On Leave"),
                ],
                default="ABSENT",
                max_length=20,
            ),
        ),
    ]
