# Generated by Django 5.2.6 on 2026-02-06 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('RESUME', 'Resume/CV'), ('ID_PROOF', 'ID Proof'), ('ADDRESS_PROOF', 'Address Proof'), ('CERTIFICATE', 'Certificate'), ('OFFER_LETTER', 'Offer Letter'), ('CONTRACT', 'Employment Contract'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('document_file', models.FileField(upload_to='employee_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
